In [2]:
import pandas as pd

In [3]:
#Brooklyn Tech Triangle coordinate boundaries gathered from pins on Google Maps
point1 = [40.703020, -74.010923] #NW Corner
point2 = [40.685979, -73.991146] #SW Corner
point3 = [40.6806397, -73.9747435] #SE corner
point4 = [40.698351, -73.972434] #NE Corner

In [4]:
#Manhattan Silicon Alley coordinate boundaries (95% of Manhattan tech companies)

point5 = (40.762261, -73.966260) #NE corner
point6 = (40.701598, -74.012487) #SE corner
point7 = (40.767958, -73.995653) #W corner

In [5]:
mta_coordinates = pd.read_csv('http://web.mta.info/developers/data/nyct/subway/StationEntrances.csv')
mta_coordinates.head()

,Division,Line,Station_Name,Station_Latitude,Station_Longitude,Route_1,Route_2,Route_3,Route_4,Route_5,...,Staffing,Staff_Hours,ADA,ADA_Notes,Free_Crossover,North_South_Street,East_West_Street,Corner,Latitude,Longitude
0,BMT,Astoria,Ditmars Blvd,40.775036,-73.912034,N,Q,NaN,NaN,NaN,...,FULL,NaN,False,NaN,True,31st St,23rd Ave,NW,40.775149,-73.912074
1,BMT,Astoria,Ditmars Blvd,40.775036,-73.912034,N,Q,NaN,NaN,NaN,...,FULL,NaN,False,NaN,True,31st St,23rd Ave,NE,40.774810,-73.912151
2,BMT,Astoria,Ditmars Blvd,40.775036,-73.912034,N,Q,NaN,NaN,NaN,...,FULL,NaN,False,NaN,True,31st St,23rd Ave,NE,40.775025,-73.911891
3,BMT,Astoria,Ditmars Blvd,40.775036,-73.912034,N,Q,NaN,NaN,NaN,...,FULL,NaN,False,NaN,True,31st St,23rd Ave,NW,40.774938,-73.912337
4,BMT,Astoria,Astoria Blvd-Hoyt Av,40.770258,-73.917843,N,Q,NaN,NaN,NaN,...,FULL,NaN,False,NaN,True,31st St,Hoyt Ave South,SW,40.770313,-73.917978

In [17]:
def max_min_coordinates(points):
    '''Function to take in coordinates of boundaries of the two tech zones. 
    Returns the max and min coordinates values to establish coordinate ranges for the two tech company clusters'''
    
    latitude = []
    longitude = []

    for point in points:
       latitude.append(point[0])
       longitude.append(point[1])

    return (max(latitude), min(latitude), max(longitude), min(longitude))

In [10]:
Brooklyn_coordinates = [point1, point2, point3, point4]
Manhattan_coordinates = [point5, point6, point7]

In [11]:
lat_max, lat_min, long_max, long_min = max_min_coordinates(Brooklyn_coordinates) 
#Filters out stations outside of max & min lat/long coordinates 
Brooklyn_list = mta_coordinates[(mta_coordinates['Station_Latitude'] >= lat_min) & (mta_coordinates['Station_Latitude'] <= lat_max)\
            & (mta_coordinates['Station_Longitude'] >= long_min) & (mta_coordinates['Station_Longitude'] <= long_max)]

In [12]:
#get unique set of subway stations within Brooklyn Tech Triangle
BK_tech_stops = set(Brooklyn_list['Station_Name'])
BK_tech_stops = list(BK_tech_stops)
BK_tech_stops

['Borough Hall',
 'Lafayette Av',
 'Lawrence St',
 'Bergen St',
 'Pacific St',
 'Nevins St',
 'Atlantic Av',
 'Fulton St',
 'Court St',
 'Jay St - Borough Hall',
 'York St',
 'Hoyt St',
 'Hoyt & Schermerhorn',
 'Atlantic Av-Barclays Ctr',
 'DeKalb Av',
 'High St',
 'Clark St']

In [13]:
lat_max, lat_min, long_max, long_min = max_min_coordinates(Manhattan_coordinates) 
#Filters out stations outside of max & min lat/long coordinates 
Manhattan_list = mta_coordinates[(mta_coordinates['Station_Latitude'] >= lat_min) & (mta_coordinates['Station_Latitude'] <= lat_max)\
            & (mta_coordinates['Station_Longitude'] >= long_min) & (mta_coordinates['Station_Longitude'] <= long_max)]

In [14]:
#get unique set of subway stations within Manhattan's 'Silicon Alley'
Manhattan_tech_stops = set(Manhattan_list['Station_Name'])
Manhattan_tech_stops = list(Manhattan_tech_stops)
Manhattan_tech_stops

['Delancey St',
 'Times Square-42nd St',
 'Franklin St',
 'Lexington Av-53rd St',
 '5th Av-53rd St',
 'Bowery',
 '59th St',
 'Broadway-Nassau',
 '3rd Av',
 '33rd St',
 '47-50th Sts Rockefeller Center',
 '5th Av',
 '28th St',
 'Canal St',
 'Brooklyn Bridge-City Hall',
 '23rd St',
 '14th St',
 'City Hall',
 'Times Square',
 '18th St',
 'Grand Central',
 '49th St',
 '6th Av',
 'Union Square',
 'Bleecker St',
 '42nd St',
 'Prince St',
 'Cortlandt St',
 '7th Av',
 'East Broadway',
 'Wall St',
 'World Trade Center',
 'Chambers St',
 'Grand St',
 'Canal St (UL)',
 'Houston St',
 'Park Place',
 '50th St',
 'West 4th St',
 'Essex St',
 'Christopher St',
 'Spring St',
 '14th St-Union Square',
 '8th Av',
 'Broadway-Lafayette St',
 '2nd Av',
 'Broad St',
 'Grand Central-42nd St',
 '57th St',
 '1st Av',
 'Fulton St',
 'Astor Place',
 'Lexington Av',
 '51st St',
 '34th St',
 '8th St']

In [15]:
combined_tech_stops = sorted(Manhattan_tech_stops + BK_tech_stops)
combined_tech_stops

['14th St',
 '14th St-Union Square',
 '18th St',
 '1st Av',
 '23rd St',
 '28th St',
 '2nd Av',
 '33rd St',
 '34th St',
 '3rd Av',
 '42nd St',
 '47-50th Sts Rockefeller Center',
 '49th St',
 '50th St',
 '51st St',
 '57th St',
 '59th St',
 '5th Av',
 '5th Av-53rd St',
 '6th Av',
 '7th Av',
 '8th Av',
 '8th St',
 'Astor Place',
 'Atlantic Av',
 'Atlantic Av-Barclays Ctr',
 'Bergen St',
 'Bleecker St',
 'Borough Hall',
 'Bowery',
 'Broad St',
 'Broadway-Lafayette St',
 'Broadway-Nassau',
 'Brooklyn Bridge-City Hall',
 'Canal St',
 'Canal St (UL)',
 'Chambers St',
 'Christopher St',
 'City Hall',
 'Clark St',
 'Cortlandt St',
 'Court St',
 'DeKalb Av',
 'Delancey St',
 'East Broadway',
 'Essex St',
 'Franklin St',
 'Fulton St',
 'Fulton St',
 'Grand Central',
 'Grand Central-42nd St',
 'Grand St',
 'High St',
 'Houston St',
 'Hoyt & Schermerhorn',
 'Hoyt St',
 'Jay St - Borough Hall',
 'Lafayette Av',
 'Lawrence St',
 'Lexington Av',
 'Lexington Av-53rd St',
 'Nevins St',
 'Pacific St',
 'Park Place',
 'Prince St',
 'Spring St',
 'Times Square',
 'Times Square-42nd St',
 'Union Square',
 'Wall St',
 'West 4th St',
 'World Trade Center',
 'York St']